#!/bin/bash

sbatch --verbose <<EOT
#!/usr/bin/env bash

#SBATCH --partition=small-g
#SBATCH --ntasks=1
#SBATCH --time=00:05:00
#SBATCH --cpus-per-task=1
#SBATCH --gpus-per-task=1
#SBATCH --output=output/slurm-%j.out

#SBATCH --account=project_462000376

source modules

./lorenz96 ${@} -j ${LORENZ96_CONFIG:-output/config_\${SLURM_JOB_ID\}.json} -o ${LORENZ96_OUTPUT:-output/state_\${SLURM_JOB_ID\}} -m ${LORENZ96_PERFORMANCE:-performance/perf_\${SLURM_JOB_ID\}}

EOT
